namespace Database.Entities.Common.Enums.Types
{
    public enum ProductTypes
    {
        FoodAndBeverages = 1,
        HomeAppliances = 2,
        BeautyAndPersonalCare = 3,
        ToysAndGames = 4,
        Footwear = 5,
        Jewelry = 6,
        Books = 7,
        Music = 8,
        VideoGames = 9,
        Appliances = 10,
        HealthAndBeauty = 11,
        HomeDecor = 12,
        Kitchenware = 13,
        OutdoorEquipment = 14,
        PetSupplies = 15,
        Stationery = 16,
        ToolsAndHardware = 17,
        Automotive = 18,
        BabyProducts = 19,
        OfficeSupplies = 20,
        Groceries = 21,
        GardenSupplies = 22,
        ArtAndCrafts = 23,
        Cameras = 24,
        CleaningSupplies = 25,
        FitnessEquipment = 26,
        MusicalInstruments = 27,
        PhonesAndTablets = 28,
        MoviesAndTV = 29,
        PersonalCare = 30,
        TravelAccessories = 31,
        SafetyAndSecurity = 32,
        MedicalSupplies = 33,
        PartySupplies = 34,
        Watches = 35,
        Eyewear = 36,
        Bedding = 37,
        Lighting = 38,
        Shoes = 39,
        Luggage = 40,
        WineAndSpirits = 41,
        HobbyCollectibles = 42,
        VideoCameras = 43,
        Drones = 44,
        NetworkingEquipment = 45,
        SmartHomeDevices = 46,
        WearableTech = 47,
        VirtualReality = 48,
    }
}
